name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FORCED_VERSION: "0.0.999-SNAPSHOT"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
      - { name: Prepare Gradle, uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc } # v2.8.0
      - name: Build with Gradle
        run: ./gradlew check
